### ISSUE TITLE
Missing file 'default.json'

### ISSUE THREAD

**Issue by haifenghuang** [vorov2/codebox#1]
When I build the solution, I got below errors:

    Could not copy the file "C:\Users\hhuang22\Desktop\slot-master\Slot\packages\slot\data\grammars\default.json" because it was not found.

**Comment by vorov2** [comment]
Can you try to simply remove it from your solution?

**Comment by haifenghuang** [comment]
I've removed the `default.json`, now when I rebuild the solution, I got below errors:

    Unhandled Exception: System.ArgumentException: The name can not be empty.
    Parameter name: oldValue
    Location System.Text.StringBuilder.Replace (String oldValue, String newValue, Int32 startIndex, Int32 count)
    Location Program.PerformJob (String fn, String path) Location C: \ Users \ hhuang22 \ Desktop \ slot-master \ Util \ BuildNumber \ Program.cs: line 71
    Location Program.Main (String [] args) Location C: \ Users \ hhuang22 \ Desktop \ slot-master \ Util \ BuildNumber \ Program.cs: line 15
    C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MS Build \ 15.0 \ Bin \ Microsoft. Common. CurrentVersion. \ Desktop \ slot-master \ Util \ Build Number \ bin \ bn. Exe "C: \ Users \ hhuang 22 \ Desktop \ slot-master \ Slot \ slot-master \ "" exited with code -532462766.

**Comment by vorov2** [comment]
Take the latest version, everything should work

**Comment by haifenghuang** [comment]
Thanks a lot for the fix, now everything is ok. 

By the way, if I build it again,  then the same error will occur.
Do I need to modify something for the second build or third build?

**Comment by vorov2** [comment]
Do you mean that you still see errors on rebuild? I can't reproduce it.

**Comment by haifenghuang** [comment]
Yes, when I built it the second time, it will report the same errors.

**Comment by vorov2** [comment]
Are you sure? Anyways errors come from a pre-build event, you can remove it manually.

**Comment by haifenghuang** [comment]
Yes, I'm sure. Ok, I'll do it as you told. Thanks a lot for the help!
